replication_factor = 1

metadata_dir = "/var/lib/garage/meta"
data_dir     = "/var/lib/garage/data"

db_engine = "sqlite"

rpc_bind_addr = "[::]:3901"

[s3_api]
api_bind_addr = "[::]:3900"
s3_region     = "garage"
